### ISSUE TITLE
nglview is not compatible with ipywidgets 7.4

### ISSUE THREAD

**Issue by IceflowRE** [arose/nglview#748]
```
>>> import nglview
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/nglview/__init__.py", line 24, in <module>
    from .widget import NGLWidget, write_html
  File "/usr/lib/python3.7/site-packages/nglview/widget.py", line 9, in <module>
    from ipywidgets import Box, DOMWidget, widget_image
ImportError: cannot import name 'widget_image' from 'ipywidgets' (/usr/lib/python3.7/site-packages/ipywidgets/__init__.py)
```
Version: `nglview-1.1.5+5.g4d88822`

**Comment by hainm** [comment]
shoud be fixed now. Thanks. Please reopen if not.
