### ISSUE TITLE
nglview fails to create view

### ISSUE THREAD

**Issue by mattchan-tencent** [arose/nglview#792]
Hi,

I can't manage to get nglview to render in my notebook.

I tried starting it using `nglview 3pqr.pdb` and also by importing it directly in a new notebook.

There is no canvas that draws and no output. An empty cell just appears on the next line and asks for input. 

- Log messages, which may or may not be relevant...

[W 17:34:25.612 NotebookApp] Notebook tmpnb_ngl.ipynb is not trusted
[I 17:34:25.818 NotebookApp] Kernel started: 027d3617-a9df-45a4-bb6a-1607050bd5b2
[I 17:34:27.081 NotebookApp] Adapting to protocol v5.1 for kernel 027d3617-a9df-45a4-bb6a-1607050bd5b2
[W 17:35:15.165 NotebookApp] 404 GET /static/nglview-js-widgets.js?v=20190426173422 (::1) 7.48ms referer=http://localhost:8888/notebooks/tmpnb_ngl.ipynb

- Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
1.2.0
python -c 'import ipywidgets; print(ipywidgets.__version__)'
7.4.2

```

**Comment by hainm** [comment]
can you please elaborate? e.g screen capture? javscript console log? 
Can you try to follow this FAQ? https://github.com/arose/nglview/blob/master/docs/FAQ.md
Thanks

**Comment by hainm** [comment]
Since I have not heard from @mattchan-tencent so I assume the case is resolved. Feel free to reopen this.

**Comment by radifar** [comment]
I am having similar issue here. 

```bash
python -c 'import nglview; print(nglview.__version__)'
2.7.5
python -c 'import ipywidgets; print(ipywidgets.__version__)'
7.5.1
```
My Jupyter Notebook:
https://gist.github.com/radifar/bd925ca4856f57f1af82e585dce99e24

Javascript console log:
```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. n-propanol rotation.ipynb
Use of Mutation Events is deprecated. Use MutationObserver instead. main.min.js:5092:11
actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later... main.min.js:55806:25
accessing "actions" on the global IPython/Jupyter is not recommended. Pass it to your objects constructors at creation time main.min.js:59437:19
Loaded moment locale en main.min.js:56714:15
load_extensions 
Arguments { 0: "nbdime/index", 1: "jupyter-js-widgets/extension", … }
main.min.js:34771:17
Loading extension: nbdime/index main.min.js:34748:29
Loading extension: jupyter-js-widgets/extension main.min.js:34748:29
accessing "actions" on the global IPython/Jupyter is not recommended. Pass it to your objects constructors at creation time 2 main.min.js:59437:19
Session: kernel_created (b5775d8c-9b74-4d2a-88c7-1bcf8fa8c3ca) main.min.js:48982:21
Starting WebSockets: ws://localhost:8890/api/kernels/ad277f4d-71d8-48e2-97b4-9131a93e2ae2 main.min.js:48140:17
Kernel: kernel_connected (ad277f4d-71d8-48e2-97b4-9131a93e2ae2) main.min.js:47784:21
Kernel: kernel_ready (ad277f4d-71d8-48e2-97b4-9131a93e2ae2) main.min.js:47784:21
Kernel: kernel_restarting (ad277f4d-71d8-48e2-97b4-9131a93e2ae2) main.min.js:47784:21
Kernel: kernel_created (ad277f4d-71d8-48e2-97b4-9131a93e2ae2) main.min.js:47784:21
Starting WebSockets: ws://localhost:8890/api/kernels/ad277f4d-71d8-48e2-97b4-9131a93e2ae2 main.min.js:48140:17
Kernel: kernel_connected (ad277f4d-71d8-48e2-97b4-9131a93e2ae2) main.min.js:47784:21
Kernel: kernel_starting (ad277f4d-71d8-48e2-97b4-9131a93e2ae2) main.min.js:47784:21
Kernel: kernel_ready (ad277f4d-71d8-48e2-97b4-9131a93e2ae2) 2 main.min.js:47784:21
The resource from “http://localhost:8890/static/nglview-js-widgets.js?v=20200609004901” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). n-propanol rotation.ipynb
Loading failed for the <script> with source “http://localhost:8890/static/nglview-js-widgets.js?v=20200609004901”. n-propanol rotation.ipynb:1:1
Could not instantiate widget manager-base.js:273
Error: "Could not create a model."
    v utils.js:119
utils.js:119
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Error: Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror 2 require.js:168:17
Could not instantiate widget manager-base.js:273
Error: "Could not create a model."
    v utils.js:119
utils.js:119
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Error: Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror require.js:168:17
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Error: "Could not create a model."
    v utils.js:119
utils.js:119
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Error: Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror require.js:168:17
Error: "Could not create a model."
    v utils.js:119
utils.js:119
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Error: "Could not create a model."
    v utils.js:119
utils.js:119
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Error: Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror 3 require.js:168:17
Could not instantiate widget manager-base.js:273
Error: "Could not create a model."
    v utils.js:119
utils.js:119
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Error: Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror require.js:168:17
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Error: "Could not create a model."
    v utils.js:119
utils.js:119
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Error: Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror require.js:168:17
Error: "Could not create a model."
    v utils.js:119
utils.js:119
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Error: "Could not create a model."
    v utils.js:119
utils.js:119
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Couldn't process kernel message Error: "Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8890/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Error: Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror 3 require.js:168:17
Source map error: Error: request failed with status 404
Resource URL: http://localhost:8890/static/notebook/js/main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316
Source Map URL: main.min.js.map
```

**Comment by radifar** [comment]
My bad, it turns out I miss one step:
` jupyter-nbextension enable nglview --py --sys-prefix`
